name: Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: pip install -r niorlusx_call_service/requirements.txt
      - run: python niorlusx_call_service/app.py & sleep 5 && pkill -f app.py
